name: Update Last.fm

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: shinokada/lastfm-readme@v1
        with:
          lastfm_api_key: ${{ secrets.LASTFM_API_KEY }}
          lastfm_username: ${{ secrets.LASTFM_USERNAME }}
